name: check vulnability

on:
  push:
    branches:
      - master
      
jobs:
  buildimage:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Setup Go execution environment
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.1
    
    - name: GitHub Script
      uses: actions/github-script@0.9.0
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '? Thanks for reporting!'
          })
      
      