name: check vulnability

on:
  push:
    branches:
      - master
      
jobs:
  Vulnability-Check:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Setup Go execution environment
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.1
    
    - name: GitHub Script
      uses: actions/github-script@v6
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: "test_issue"
          });
      